### ISSUE TITLE
manage permission for PyPI

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx-intl#100]
Currently I have no PyPI permission to upload new releases.
It appears that my permissions were lost when the PyPI sphinx organization was set up in April 2023.

@AA-Turner Please set one of the following permissions:

- manage sphinx-intl package: https://pypi.org/manage/organization/sphinx/projects/
- sphinx organization as a manager: https://pypi.org/manage/organization/sphinx/people/

**Comment by AA-Turner** [comment]
@shimizukawa I've added you back -- sorry for the oversight!

A

**Comment by shimizukawa** [comment]
@AA-Turner Confirmed. Thanks for setting up the permissions so quickly!
