### ISSUE TITLE
Sidebar titles don't localize 

### ISSUE THREAD

**Issue by tolmachguidev** [sphinx-doc/sphinx-intl#11]
Running `sphinx-intl` on Windows, I get [sidebar titles](http://docutils.sourceforge.net/docs/ref/rst/directives.html#sidebar) excluded from `po` files. Whereas under OS X, these titles are successfully added for localization.
Is there any way to include sidebar titles under Windows?

**Comment by tolmachguidev** [comment]
I noticed that sidebar title localization has broken in `sphinx-docs`. Please compare:
http://www.sphinx-doc.org/ja/1.5/tutorial.html
http://www.sphinx-doc.org/ja/stable/tutorial.html

**Comment by shimizukawa** [comment]
I think there is no differences on Windows and Mac.

> I noticed that sidebar title localization has broken in sphinx-docs. Please compare:
> http://www.sphinx-doc.org/ja/1.5/tutorial.html
> http://www.sphinx-doc.org/ja/stable/tutorial.html

Currently, above both pages is not broken.

Is three any small sample to reproduce the issue?

**Comment by tolmachguidev** [comment]
Dear Takayuki,

I mean that localization of sidebar title doesn't work now:
Please, have a look at the following pages (the former has localized title):
http://www.sphinx-doc.org/ja/1.4/tutorial.html
http://www.sphinx-doc.org/ja/1.5/tutorial.html

Here is the example where you can see that title wasn't added to po file:

https://github.com/tolmachguidev/test-sphinx-l10n/blob/master/locale/ru/LC_MESSAGES/index.po

**Comment by shimizukawa** [comment]
Ah, I see. I guess it is a bug of sphinx (around `make gettext`). sphinx-intl does not control which range is to be translated. Please report to Sphinx's tracker: https://github.com/sphinx-doc/sphinx/issues

**Comment by shimizukawa** [comment]
Now I close this issue.  Thanks.
