### ISSUE TITLE
The file sphinx-intl/tests /conftest.py is missing from the PyPi archive

### ISSUE THREAD

**Issue by a-detiste** [sphinx-doc/sphinx-intl#112]
https://files.pythonhosted.org/packages/74/67/c7e73f8cf020db01d052d0507ba60fbd10eae018e47be8294a2cda5b940e/sphinx_intl-2.3.0.tar.gz

**Comment by a-detiste** [comment]
path.py too

**Comment by shimizukawa** [comment]
Thanks. I'll take a look it soon.

**Comment by shimizukawa** [comment]
Fixed by #113.
I'll make a relese in few days.

**Comment by a-detiste** [comment]
Thank you

**Comment by shimizukawa** [comment]
Now 2.3.1 has been released.
https://pypi.org/project/sphinx-intl/2.3.1/

**Comment by a-detiste** [comment]
Thanks
