### ISSUE TITLE
How do you deal with image internationalization?

### ISSUE THREAD

**Issue by tong822218** [sphinx-doc/sphinx-intl#13]
How do you deal with image internationalization?

**Comment by shimizukawa** [comment]
For now, internationalization of images is not within the scope of sphinx-intl handling. sphinx-intl focuses on pot file handling only. For internationalization of images, it is necessary to have image files for each language in the document itself.
http://www.sphinx-doc.org/en/stable/config.html?highlight=image%20language#confval-figure_language_filename

I have no idea yet, but please let me know if you have any good workflow and feature ideas.

**Comment by shimizukawa** [comment]
Now I close this issue.  Feel free to reopen if you have any update. Thanks!

**Comment by tong822218** [comment]
ok,thanks
