### ISSUE TITLE
Sidebar menus are not translated

### ISSUE THREAD

**Issue by julienmalard** [sphinx-doc/sphinx-intl#19]
Sidebar menu links which are given as titles in DOCtree directives never make it to the .pot files for translation.
For instance, the items of the Index (சுட்டுவரிசை) in the translated page http://tinamit.readthedocs.io/ta/latest/index.html are not translated, nor is the sidebar based on it.

**Comment by shimizukawa** [comment]
sphinx-intl does not control which range is to be translated. Please report to Sphinx's tracker: https://github.com/sphinx-doc/sphinx/issues

ex.: https://github.com/sphinx-doc/sphinx/issues/1872
