### ISSUE TITLE
No way to to create MO files in a separate directory.

### ISSUE THREAD

**Issue by ideasman42** [sphinx-doc/sphinx-intl#2]
Creating the MO files next to the PO files is problematic for source control, which may try to remove directories on updating (which will fail if files out of source control are present), less experienced translators may accidentally commit the MO files too (this just happened in fact).

Ideally: `sphinx-intl build` could take an `--output-dir` argument.

If this is acceptable, I can write up a patch to add support for this.

**Comment by shimizukawa** [comment]
Now I've merged #3. Thanks!
