### ISSUE TITLE
Internationalization with multi project sphinx setup not using .po files

### ISSUE THREAD

**Issue by OskarPersson** [sphinx-doc/sphinx-intl#20]
I have a some projects which all uses the same core project. For these projects I've setup sphinx to generate the same core documentation in all projects and mix it with each project specific documentation using a simple symbolic link.

```
$ cd /path/to/subproject/a/docs
$ ln -s /path/to/coreproject/docs core
$ make html
```

Now I want to have internationalization using `sphinx-intl` but I can't get the documentation from the core project to to use the `.po` files.

I've tried setting locale_dirs = ['locale/', 'core/locale/'] and then running the following commands from my subproject:

```
$ make gettext
$ sphinx-intl update -p _build/gettext -l sv
$ make -e SPHINXOPTS="-D language='sv'" html
```

---

I've also created a question on stackoverflow [here](https://stackoverflow.com/questions/48440506/internationalization-with-multi-project-sphinx-setup)

**Comment by shimizukawa** [comment]
@OskarPersson I think your project structure doesn't work well for i18n of sphinx becaues:

- `/path/to/subproject/a/docs`  expects locale files like: `index.po` and `core.po`.
- `/path/to/subproject/a/docs/core/locale` provides `index.po` instead of `core.po`

I think that you can get the expected behavior if you set it like the following:

1. set `gettext_compact = True` to all of `conf.py`.
2. symlink like bellow:
```
$ cd /path/to/subproject/a/docs/locale/sv/LC_MESSAGES/
$ ls
core  index.po
$ rm -R core
$ ln -s /path/to/coreproject/docs/locale/ja/LC_MESSAGES core
```
`subproject` expect `core/*` message catalog files for each `docs/core` files and now there are.

I think this solution is not  a proper way (and no proper way), but it worked in my environment.

**Comment by OskarPersson** [comment]
Can you list the complete workflow? I can't get it to work on my machine. The translated text from core is not used.

Why is `rm -R core` needed? I only have `index.po` and `core.po` in `/path/to/subproject/a/docs/locale/sv/LC_MESSAGES/` and if I delete `core.po` I get an error message saying that `core.po` is missing.

What should `locale_dirs` be set to?

---

Also, I'm guessing the last line should be `/path/to/coreproject/docs/locale/sv/LC_MESSAGES` instead of `/path/to/coreproject/docs/locale/ja/LC_MESSAGES`? :)

**Comment by shimizukawa** [comment]
please try:
```
mkdir -p docs/coreproject
cd docs/coreproject
sphinx-quickstart -q -p 1 -v 1 -a 1 docs
cd ..  # go to docs
mkdir -p subproject/a
cd subproject/a
sphinx-quickstart -q -p 2 -v 2 -a 2 docs
cd docs/
ln -s ../../../coreproject/docs core
mkdir locale
cd ../../../coreproject/docs
mkdir locale
make gettext
sphinx-intl -p _build/gettext -l sv
sphinx-intl update -p _build/gettext -l sv
vi locale/sv/LC_MESSAGES/index.po   # modify po
make html SPHINXOPTS="-D language=sv"
# confirm 'core' _build/html/index.html 
cd ../subproject/a/docs/
make gettext
sphinx-intl update -p _build/gettext -l sv
cd locale/sv/LC_MESSAGES/
ls
rm -R core
ln -s ../../../../../../coreproject/docs/locale/sv/LC_MESSAGES core
vi index.po   # another modify
cd ../../..
make html SPHINXOPTS="-D language=sv"
# confirm 'sub' _build/html/index.html
```

project files: https://www.dropbox.com/s/cd65jt4h0x31cse/sphinx-intl-issue-20-docs.tar.gz?dl=0

**Comment by OskarPersson** [comment]
That works great, thank you!

You mentioned that my project structure didn't work well, do you have any other suggestions for my scenario (core project with different subprojects)?
