### ISSUE TITLE
Not working on Windows 

### ISSUE THREAD

**Issue by haschdl** [sphinx-doc/sphinx-intl#22]
I followed exact steps in read me and in Sphinx documentation, but the output is always in English.  All in all `sphinx-intl` documentation is not very clear, leaving a lot of room for trial and error.

Documentation says `make gettext will generate pot files into _build/locale directory` however running `make gettext` always generates files in `_build\gettext` folder.

**Comment by shimizukawa** [comment]
Thanks for your reporting. Your point is correct. 
Historically, `make gettext` was generate pot files into `_build/locale`.
I'll fix the document soon.

**Comment by haschdl** [comment]
hello @shimizukawa, thanks for looking into the issue I reported, I'm glad to see you active in the project.

I'm still a bit confused on how the `sphinx-intl` should work. My main question at the moment, should the output in `_build` folder contain the original language, plus translations?   Following the instructions you provided, `_build` always contains either the original language of the project, or the translated language. If I want to provide documentation in two languages, what is the required setup? The documentation is not clear in this respect.

**Comment by shimizukawa** [comment]
I also don't think current documentation is nice..
For now, please refer https://www.slideshare.net/shimizukawa/easy-contributable-internationalization-process-with-sphinx-at-pycon-apac-2016
