### ISSUE TITLE
How to automatically access each language version documents by browser settings?

### ISSUE THREAD

**Issue by rkdls** [sphinx-doc/sphinx-intl#26]
Thank you for your repository!

Maybe It's a very foolish question.

I successfully generated Korean version documents and English version.

And I thought It can be redirected to Korean version if my browser set up with Korean (vice versa), but It's not.

Is there any guide to setup or reference?

again, Thank you for your effort!

**Comment by shimizukawa** [comment]
Sphinx and sphinx-intl doesn't provide "language switcher" mechanism.

However ReadTheDocs provides it.
Please refer https://docs.readthedocs.io/en/latest/guides/manage-translations.html.
Thanks
