### ISSUE TITLE
Add an option for configuring the maximum line width of the generated PO files

### ISSUE THREAD

**Issue by armandciejak** [sphinx-doc/sphinx-intl#28]
It is currently not possible to configure it, the Babel default is used (76). Having the possibility to configure it would help when working with graphical PO editors like poedit which usually wrap line at 80 characters.
When using such an editor with the PO files tracked in a version control system, the diff are useless: all lines change because of the line being wrapped differently by sphinx-intl and the editor.

**Comment by tk0miya** [comment]
+0; I'll approve if PR has come.

Note: It seems `babel.messages.pofile.write_po()` takes `width` argument. So it would be able to change easily.
http://babel.pocoo.org/en/latest/api/messages/pofile.html?highlight=write_po#babel.messages.pofile.write_po

**Comment by shimizukawa** [comment]
merged #29
