### ISSUE TITLE
Customize po header

### ISSUE THREAD

**Issue by TisonKun** [sphinx-doc/sphinx-intl#36]
```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2019, TubeMQ Team
# This file is distributed under the same license as the TubeMQ package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: TubeMQ \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-10-29 20:40+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"
```

I'd like to customize LICENSE header as well as no `"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"` and `"Language-Team: LANGUAGE <LL@li.org>\n"` and `# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.`

Is there an option to do that instead of manually remove then from generated?

**Comment by tk0miya** [comment]
Are you saying about the pot file generated by `make gettext`? If so, it is an issue of sphinx, not sphinx-intl.

**Comment by TisonKun** [comment]
Yes correct. I think `sphinx-intl update -l <lang>` just extracts from pot files.

**Comment by TisonKun** [comment]
FYI https://github.com/sphinx-doc/sphinx/issues/6781

**Comment by shimizukawa** [comment]
Thanks for your reporting. I'm going to close this `sphinx-intl` side issue.
