### ISSUE TITLE
Documentation corrections

### ISSUE THREAD

**Issue by ynikitenko** [sphinx-doc/sphinx-intl#39]
I read your documentation, and noticed several errors or typos. I report the most obvious ones.
It would be great if a native speaker could read that all and correct. Thanks for your work.

> Please install sphinx-intl with using pip (8.1.1 or later).

better:
Please install sphinx-intl using pip (8.1.1 or later). (or only with)
https://sphinx-intl.readthedocs.io/en/master/quickstart.html#installation

This section describe**s how**  to translate with Sphinx and sphinx-intl command.
https://sphinx-intl.readthedocs.io/en/master/quickstart.html#quickstart-for-sphinx-translation

This invoke**s** the sphinx gettext builder that generates *.pot files under _build/gettext directory.
(same link below)

After this, you got (better **get**?) these directories that contain po files:

For more information, please refer **to** References.
https://ell.stackexchange.com/questions/58525/what-is-the-difference-between-refer-the-letter-and-refer-to-the-letter

When I run 

```
$ sphinx-intl update -p _build/gettext -l ru
Usage: sphinx-intl update [OPTIONS]

Error: Invalid value for pot_dir: '_build/gettext' is not exist. 
Please specify pot directory with -p option,
or preparing your pot files in '_build/gettext'.
```

the error message must be **does not exist** (not *is*). **or prepare**.

Type sphinx-intl without arguments * - remove, options)* to show command help.
https://sphinx-intl.readthedocs.io/en/master/refs.html

Dashes (-) have to **be** replaced with underscores (_).

*(redundant) This * is the same as passing the option to sphinx-intl directly:

Add below settings to sphinx document’s conf.py if **they do not exist**:

however pot files should be generated in the locale/pot is convenient. You can be done by replacing 
-- **pot files generated in the locale/pot are convenient.** (think of rewriting that)

Definition of be done with (not **by**)
: to bring to completion : to finish 
https://www.merriam-webster.com/dictionary/be%20done%20with
If you are sure this is what you want to say, that's fine. For me it sounds a bit vague. Simple words may be better here. **You can solve this by...**

**Comment by tk0miya** [comment]
Thanks,
Could you make a pull request please?

**Comment by ynikitenko** [comment]
The problem is I'm not a native speaker. I wanted other people to check what I suggested and maybe propose other things (especially what concerns stylistics). If another person adds these corrections, there would be at least two people who watched them. Also, if you have the source, it may be easier for you to introduce these changes (I installed from pip).

**Comment by tk0miya** [comment]
I'm also not a native speaker. And there are no native speakers on our project. Is it better to wait any native speakers has come? I think No. It would be better to update our documents as possible. I think you have much better English skills than me. So I need your help for updating our documents.

**Comment by ynikitenko** [comment]
I understand. However, I wrote my suggestions. You can just use them as they are. You probably know the location of these phrases better. Moreover, there is a phrase from program output, which might be hard for me to find...

**Comment by tk0miya** [comment]
Okay, I'll try to fix them if I have time.

**Comment by tk0miya** [comment]
I posted PR #40 now to fix this.

>Definition of be done with (not by)
: to bring to completion : to finish
https://www.merriam-webster.com/dictionary/be%20done%20with
If you are sure this is what you want to say, that's fine. For me it sounds a bit vague. Simple words may be better here. You can solve this by...

What did you mean? I can't find wrong document.

**Comment by ynikitenko** [comment]
In the end of https://sphinx-intl.readthedocs.io/en/master/refs.html#makefile-make-bat it's written
"You can be done by replacing"
I think it could be better formulated as "You can achieve this by replacing". 
Many thanks that you did it! I was thinking about that, but was also very busy.

**Comment by tk0miya** [comment]
Thanks. I found it.

**Comment by tk0miya** [comment]
Fixed now.

**Comment by ynikitenko** [comment]
Many thanks for your work and time! Glad the program has improved even further :)
