### ISSUE TITLE
Different TX Config ordering for Windows and Linux

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx-intl#41]
Seems like the ordering is completely different for Windows and Linux. On Windows it seems to sort alphabetical while on my linux machine it's quite haphazard. 

This completely breaks cross-platform usability.

**Comment by tk0miya** [comment]
At the latest release, we fixed the sorting bug of `.tx/config` (see #38). Do you use it?

**Comment by tk0miya** [comment]
OMG, I noticed my last release was in development status. I'm sorry. I'll ship it as a final version tomorrow. Please wait a little.
https://pypi.org/project/sphinx-intl/2.0.1.dev20200411/

**Comment by tk0miya** [comment]
I just bumped the final version; v2.0.1 now.
@Daltz333 Could you check it please?

**Comment by AustinShalit** [comment]
Thank you for releasing. v2.0.1 resolved the issue.

**Comment by tk0miya** [comment]
Thank you for confirming!
