### ISSUE TITLE
allow to specify translation context

### ISSUE THREAD

**Issue by alex-tee** [sphinx-doc/sphinx-intl#43]
For Russian, some users said they wanted to have separate translations for the same source strings. This is accomplished by translation contexts, eg:

```gettext
#: src/gui/widgets/preferences.c:858
msgctxt "guilabel"
msgid "Plugins"
msgstr "プラグイン"
```

please make it possible to specify a translation context. if not for individual strings, at least make it possible to specify a context for the whole project that sphinx-intl is processing (since my translations are shared with other projects). maybe add a command line option `--context`?

**Comment by tk0miya** [comment]
I think this proposal should be posted to the sphinx core instead of sphinx-intl because it does not support the context feature. TBH, I don't know about the feature at all. So it would be helpful if you contribute to the core :-)

**Comment by alex-tee** [comment]
thanks, opened https://github.com/sphinx-doc/sphinx/issues/8251 with more details
