### ISSUE TITLE
Having .po files in one folder for each language

### ISSUE THREAD

**Issue by huxaiphaer** [sphinx-doc/sphinx-intl#48]
Is there a possibility of having `.po` files in one place rather than having each one in a separate folder ?

**Comment by tk0miya** [comment]
Could you try to pass a string to `gettext_compact`?
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_compact

**Comment by huxaiphaer** [comment]
What do you mean by passing a string @tk0miya , would you mind expanding your comment a bit ? Thanks

**Comment by tk0miya** [comment]
The `gettext_compact` is a configuration of sphinx. So please add the following line to your conf.py

```
gettext_compact = 'filename'
```

**Comment by huxaiphaer** [comment]
Maybe my last question is, how can I separate the concerns of saving in file for English and one file for Germany for example when am translating @tk0miya

**Comment by tk0miya** [comment]
Thank you for explanation. Unfortunately, there is no way to do that. Please put .po file to the directory for each language.
