### ISSUE TITLE
[Urgent] Update Transifex Calls to APIv3

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx-intl#60]
See notice at the top of https://docs.transifex.com/api/introduction

This tool will no longer be functional as of April 7th.

![image](https://user-images.githubusercontent.com/10674555/157069022-a00b9c49-9237-41ac-84fb-c46b8873cdcc.png)

**Comment by Daltz333** [comment]
Whoops, I incorrectly assumed this tool made calls to the transifex api. After digging through the source, this does not seem to be the case.

**Comment by shimizukawa** [comment]
Thanks for your reporting!

As you are aware, sphinx-intl does not call transifex-api. However, it uses transifex-client, which is deprecated in accordance with the API.
https://github.com/sphinx-doc/sphinx-intl/blob/6edc8aaf803ee9ab1285920a41577a69e774f05e/setup.py#L14-L17

Therefore, we need to switch to calling the new [transifex cli](https://github.com/transifex/cli/releases) by the end of 2022.

**Comment by rffontenelle** [comment]
@shimizukawa Actually, [sphinx_intl/transifex.py](https://github.com/sphinx-doc/sphinx-intl/blob/28b10657560edb0d6c72eb26c851cbed7f8c02ad/sphinx_intl/transifex.py) seems to `import txclib.utils`, so it also relies on a Python library that will not be available in the [new golang implementation of the CLI tool](https://github.com/transifex/cli).
