### ISSUE TITLE
How response to the source document updates?

### ISSUE THREAD

**Issue by hellorayza** [sphinx-doc/sphinx-intl#63]
I noticed that execete 
```
make gettext
sphinx-intl  update -l <lang>
```
the regenerated `.po`  file retained the previous translation content, 
but I only saw the file update prompt on the terminal during executed command, 
so how does the translator know which files was updated and  need to translate?  
Something like adding an update tag in the appropriate place in the `.po`  file?  
I have also learned that [transifex provide XLIFF file ](https://docs.transifex.com/formats/gettext#download-options) containd  untranslated content, but this feature is available in the paid version.  

Thank you for any guidance.

**Comment by rffontenelle** [comment]
Normally, when Gettext PO file are updated and it has new strings that are similar to another which was translated already, then it receives the translation and also a `, fuzzy` flag. This is a fuzzy-flagged string that will not show its translation in the compiled software/docs until translators act upon it and remove the flag.

If I remember correctly, Transifex does not import translations from fuzzy-flag strings. Instead Transifex has it own system of suggestions, which may find a similar translation from the Translation Memory (TM).

Back to the Terminal, I'd normally run `git diff` after `sphinx-intl update` command to find which PO files were updated.
