### ISSUE TITLE
Transifex's tx client seems to have changed behavior for resource naming

### ISSUE THREAD

**Issue by jpmckinney** [sphinx-doc/sphinx-intl#88]
Previously, I could use the .tx/config file created by `sphinx-intl update-txconfig-resources` to upload resources, whose name would match the resource ID, e.g. "tariffs--1_1--codelists", which comes from normalizing the resource's local file path.

Now, in Transifex, for new resources, the resource shows up with a name that corresponds to the basename of the `source_file`, e.g. `codelists.pot`.

The earlier behavior can be restored by setting `resource_name` in the config file (i.e. adding `--resource-name` to the `tx add` command in `transifex.py`).

If this project doesn't want to hardcode `resource_name` to the resource ID, I would appreciate an opt-in flag for this behavior.

**Comment by jpmckinney** [comment]
I don't think this is a limitation of the new `tx` client. I've made a PR with the necessary change. https://github.com/sphinx-doc/sphinx-intl/pull/90 With this PR, I get exactly the behavior I want from the issue description.

The problem is that, if `resource_name` is not set, then the new `tx` client performs differently than it did before.

**Comment by rffontenelle** [comment]
Glad to be wrong and to see a PR for this. Thanks!
