### ISSUE TITLE
Footnotes not rendering as expected in localized version when using myst parser

### ISSUE THREAD

**Issue by thorge** [sphinx-doc/sphinx-intl#91]
I have a Sphinx documentation project where I'm writing content in Markdown using the myst parser. In the default English version of the documentation, footnotes are formatted correctly, and I'm getting properly rendered footnotes in the resulting HTML when I build the documentation.

However, I've also created a localized German version of the documentation, and while the translation seems to work fine overall, I'm encountering an issue with footnotes. In the German version, the footnotes are not being converted to the correct HTML format. Instead of seeing the formatted footnotes as in the English version, it appears that the German version is simply printing the Markdown string, like `[^1]`, without converting it to the expected HTML footnote markup.

The .po files look fine, e.g.:

```po
#: ../test.md:1
msgid ""
"Test [^1]"
msgstr ""
"Test [^1]"
```
I expect that when I build the German version of the documentation, the footnotes should be processed and rendered in the same way as they are in the original English version. Other markdown features also work without interfering with the locales. Any idea what I am missing?

**Comment by AA-Turner** [comment]
We don't support myst parser -- please could you either check that the issue persists with reST or report to myst?

A

**Comment by thorge** [comment]
> We don't support myst parser -- please could you either check that the issue persists with reST or report to myst?

In reST everything works, but footnotes are noted differently. I will report to myst, thanks.
