### ISSUE TITLE
Release 2.2.0?

### ISSUE THREAD

**Issue by jpmckinney** [sphinx-doc/sphinx-intl#98]
It has been a year since 2.1.0, and the bug fix from #90 would be really great.

**Comment by jpmckinney** [comment]
If maintainer capacity is the constraint, I am the maintainer of many PyPI projects, notably [csvkit](https://csvkit.readthedocs.io/en/latest/) and [scrapyd](https://scrapyd.readthedocs.io/en/latest/), both of which have higher downloads, issue creation, etc. than sphinx-intl. I am not the original maintainer of those projects, either.

**Comment by rffontenelle** [comment]
@shimizukawa sorry for pinging you, but could please consider this request? The aforementioned bug fix is indeed important. Even Sphinx documentation translation is affected by the lack of resource_name in .tx/config.

**Comment by shimizukawa** [comment]
OK, I will try to set aside some time over the weekend.
Sorry for the late reply.

**Comment by shimizukawa** [comment]
2.2.0 has now shipped!
https://pypi.org/project/sphinx-intl/2.2.0/
Thank you for your patience.
